apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-app-staging
  namespace: argocd
spec:
  destination:
    namespace: app-staging
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/lbogdan/example-app.git
    path: helm
    helm:
      releaseName: example-app
      values: |-
        environment: staging

        image:
          registry: cr.37-27-0-62.sslip.io
          tag: v0.0.15

        ingress:
          enabled: true
          host: app-staging.k8s.lbogdan.ro
          # tls: true
