apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: ingress-nginx
    helm:
      valueFiles:
      - $values/infra/helm/ingress-nginx-values.yaml
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.8.2
  - repoURL: https://github.com/lbogdan/gitops-test.git
    ref: values
