apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: metrics-server
    helm:
      valueFiles:
      - $values/infra/helm/metrics-server-values.yaml
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 6.5.5
  - repoUrl: https://github.com/lbogdan/gitops-test.git
    ref: values
