# affinity:
#   nodeAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: node-role.kubernetes.io/control-plane
#           operator: Exists
apiService:
  create: true
extraArgs:
- --kubelet-preferred-address-types=InternalIP
priorityClassName: system-cluster-critical
# tolerations:
# - effect: NoSchedule
#   key: node-role.kubernetes.io/control-plane
#   operator: Exists
